# This is a basic workflow for docker image build and push
#
#  Builds docker image and push it to docker registry useng basic authorization
#  Requires
#    actions-runner-controller inside k8s cluster with dind without container
#  Can be used from another repository with https://docs.github.com/en/actions/learn-github-actions/reusing-workflows
#  Caller repository reuired
#    Dockerfile 
#    Secret envs 


name: Build image

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_call:
    secrets:
      RUNNER_GITHUB:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true
      IMAGE_NAME:
        required: true
      IMAGE_TAG:
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    name: Get release
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Get tags for images
        uses: actions/github-script@v5
        id: get-release
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
        with:
          script: |
            console.log(context.ref)
            if ( context.ref.match(/refs\/tags\/.*/)) {
              const result = "release"
              return result
            } else {        
              const result = "latest"
              return result
            }

      - name: Get tags
        id: get-tags
        run: |
         env

      - name: List tags
        run: |
          echo ${{ steps.get-tags.outputs.docker_tag }}
          echo ${{ steps.get-tags.outputs.docker_tag_custom }} 


      - name: setup docker context for buildx
        id: buildx
        run: |
          docker context create builders
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1
        with:
          endpoint: builders

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          # registry: docker.com
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build image and push to Docker Hub and GitHub Container Registry
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          # builder: ${{ steps.buildx.outputs.name }}
          # relative path to the place where source code with Dockerfile is located
          context: .
          # Note: tags has to be all lower-case
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.IMAGE_NAME }}:${{ steps.get-tags.outputs.docker_tag }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.IMAGE_NAME }}:${{ steps.get-tags.outputs.docker_tag_custom }}
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
